### ISSUE TITLE
mac gulp dev 报错

### ISSUE THREAD

**Issue by Oscar-ren** [panteng/wechat-h5-boilerplate#11]
fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.getInstalledBinaries (/Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:119:13)
    at foundBinariesList (/Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

node版本是0.12.2，之前用windows没问题，现在换了mac报错了，不知道为什么，两个电脑node版本是一样的，研究很久也不知道怎么回事，求助，谢谢

**Comment by panteng** [comment]
看样子是node-sass出了问题，请确认你的mac已经正确配置了node-gyp，并且在npm install -d 过程中没有报错

**Comment by Oscar-ren** [comment]
非常感谢你这么晚了还来回答我的问题，这是我检查的信息
renxiangleideMacBook-Pro:summer_h5 renxianglei$ npm info node-gyp -v
2.7.4
renxiangleideMacBook-Pro:summer_h5 renxianglei$ npm install -d
npm info it worked if it ends with ok
npm info using npm@2.7.4
npm info using node@v0.12.2
npm info preinstall wechat-h5-boilerplate@0.3.5
npm WARN package.json gulp-minify-css@1.2.4 No repository field.
npm info build /Users/renxianglei/IdeaProjects/summer_h5
npm info linkStuff wechat-h5-boilerplate@0.3.5
npm info install wechat-h5-boilerplate@0.3.5
npm info postinstall wechat-h5-boilerplate@0.3.5
npm info prepublish wechat-h5-boilerplate@0.3.5
npm info ok 

我也怀疑是node-sass的问题，我npm install gulp-sass的时候一直卡住不动，信息如下

npm WARN package.json gulp-minify-css@1.2.4 No repository field.
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
/

> node-sass@3.8.0 install /Users/renxianglei/IdeaProjects/summer_h5/node_modules/gulp-sass/node_modules/node-sass
> 
> ## node scripts/install.js

能看出来是哪里出的问题吗？谢谢

**Comment by panteng** [comment]
如果你确认是按照node-gyp官网的步骤在mac上配置了node-gyp的话，那么有两种解决方案，第一种是在安装gulp-sass时如果卡住，就再耐心等一下，我也遇到过卡住半天不动的情况，但是等了好一会之后就继续正常安装了。第二种是放弃gulp-sass，使用gulp-less，但是你要自己手动修改相关的gulp任务，将原来的编译sass的任务改为编译less。
总之我认为是node-sass没有安装成功。

**Comment by panteng** [comment]
另外我建议你把node.js和npm升级到最新版本~

**Comment by Oscar-ren** [comment]
我改了代理地址后就可以了，原来是因为下载包文件的时候被墙网速超慢，麻烦你了，谢谢你之前及时的回复

**Comment by panteng** [comment]
酷~
