### ISSUE TITLE
添加第三方库的时候出错

### ISSUE THREAD

**Issue by lincx** [panteng/wechat-h5-boilerplate#17]
添加第三方库（重力感应：https://github.com/shrekshrek/orienter）会出错：

require('./orienter/orienter.js')
var o = new Orienter();
o.init();
出错，提示：Uncaught ReferenceError: Orienter is not defined。
请问是什么原因造成的？

**Comment by panteng** [comment]
也许你应该尝试在vendors.js中引入orienter.js。

**Comment by dovegq** [comment]
>gulp dev

/data/www/default/h5/node_modules/gulp-imagemin/index.js:2
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/www/default/h5/gulpfile.js:9:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

这是什么情况

**Comment by dovegq** [comment]
执行一下命令解决
npm cache clean -f
sudo npm install -g n
sudo n stable
node --version
npm install gulp-sass
