### ISSUE TITLE
gulp prod has error

### ISSUE THREAD

**Issue by aLIEzsss4** [panteng/wechat-h5-boilerplate#24]
`events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (H:\h50121\node_modules\.2.1.2@gulp-uglify\lib\create-error.js:6:14)
    at wrapper (H:\h50121\node_modules\.4.17.4@lodash\_createHybrid.js:87:15)
    at trycatch (H:\h50121\node_modules\.2.1.2@gulp-uglify\minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (H:\h50121\node_modules\.2.1.2@gulp-uglify\minifier.js:79:19)
    at DestroyableTransform.Transform._read (H:\h50121\node_modules\.2.3.3@readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (H:\h50121\node_modules\.2.3.3@readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (H:\h50121\node_modules\.2.3.3@readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (H:\h50121\node_modules\.2.3.3@readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (H:\h50121\node_modules\.2.3.3@readable-stream\lib\_stream_writable.js:322:11)
    at write (H:\h50121\node_modules\.1.0.34@readable-stream\lib\_stream_readable.js:623:24)`

**Comment by aLIEzsss4** [comment]
es6=>es5

**Comment by zjxpcyc** [comment]
@aLIEzsss4 我也遇到了这个问题，你怎么解决的？
