### ISSUE TITLE
Error running npm install after upgrading node 

### ISSUE THREAD

**Issue by Gudu4Real** [panteng/wechat-h5-boilerplate#28]
2385 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
2386 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
2387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2388 verbose stack Error: node-sass@4.7.2 install: `node scripts/install.js`
2388 verbose stack spawn bash ENOENT
2388 verbose stack     at _errnoException (util.js:1022:11)
2388 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
2388 verbose stack     at onErrorNT (internal/child_process.js:372:16)
2388 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2388 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
2389 verbose pkgid node-sass@4.7.2
2390 verbose cwd E:\node\wechat-h5-boilerplate
2391 verbose Windows_NT 10.0.16299
2392 verbose argv "E:\\node\\node.exe" "E:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
2393 verbose node v8.10.0
2394 verbose npm  v5.7.1
2395 error file bash
2396 error path bash
2397 error code ELIFECYCLE
2398 error errno ENOENT
2399 error syscall spawn bash
2400 error node-sass@4.7.2 install: `node scripts/install.js`
2400 error spawn bash ENOENT
2401 error Failed at the node-sass@4.7.2 install script.
2401 error This is probably not a problem with npm. There is likely additional logging output above.
2402 verbose exit [ 1, true ]

**Comment by Gudu4Real** [comment]
Use Node 6.0.0 
npm 3.8.6 

the problem should go away
